### ISSUE TITLE
summernote now has an official integration

### ISSUE THREAD

**Issue by dandv** [flanamacca/summernote-standalone#1]
https://github.com/HackerWins/summernote/tree/develop/meteor

Might want to work there on a dependency-less integration?

**Comment by flanamacca** [comment]
Urgh sorry mate - been help up with a few things.

Basically summernote can sometimes be used in bootstrap and non bootstrap environments (so either or cause problems if selected).  Additionally, a lot of the elements (font awesome especially) are customized quite a bit by some theming tools so that plays a part too
